name: Pentestingtools Moniter

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches:
      - main

# Actions project permission
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Generating README.md with New Tools
      run: |
        sed -i '/## View in Markdown:/q' README.md
        sed -i "/## View in Markdown:/a $(cat tools.json | go run markdown-generator.go | sed 's/[&/\]/\\&/g' | tr '\n' '\0' | sed 's/\x0/\\n/g')" README.md

    - name: Commit and push changes if there are any
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add .

        # Check if there are changes before committing
        if ! git diff --cached --exit-code; then
          IST_DATE=$(TZ='Asia/Kolkata' date +'%a %b %d %H:%M:%S IST %Y')
          git commit -m "Updated List: $IST_DATE"
          git push
        else
          echo "No changes to commit"
        fi